apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: web-3
  name: web-3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web-3
status:
  loadBalancer: {}
